### ISSUE TITLE
Translation to brazilian portuguese

### ISSUE THREAD

**Issue by vilaboim** [yangshun/front-end-interview-handbook#167]
Hi guys, how are you?

I would like to know how is the translation to brazilian portuguese going?
I saw some issues about it, nothing more.

Could I start a translation?

**Comment by pedro-surf** [comment]
Hi, 
Let's write and help others!
I found it [here](https://github.com/yangshun/front-end-interview-handbook/tree/master/Translations/Portuguese). It's written in Portugal portuguese, however I had to check where the author is from, because I couldn't really tell whether it was or not brazilian portuguese. Do you think that a separated one would be needed?

Thi

**Comment by yangshun** [comment]
PRs welcome. I will not actively seek translations for other languages, interested parties can create PRs with some implementation efforts.
