### ISSUE TITLE
Recommendation to not check for null

### ISSUE THREAD

**Issue by roblevintennis** [yangshun/front-end-interview-handbook#204]
This is nuanced and perhaps debatable too haha. I happened to be reading an example polyfill in the MDN [docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Polyfill) on `Object.assign` and they do:

`if (target == null) { // TypeError if undefined or null`

If I'm understanding your https://github.com/yangshun/front-end-interview-handbook/blob/master/questions/javascript-questions.md#whats-the-difference-between-a-variable-that-is-null-undefined-or-undeclared-how-would-you-go-about-checking-for-any-of-these-states section

you're advising that you should not take advantage of the fact that

```javascript
null === undefined
false
null == undefined
true
```

I usually would agree, but would you say they're example is a misuse of loose checking? I could see it written as:

`if (target === null || target === undefined) {`

So my issue here is probably not more of an issue then discussion (so feel free to close). But, I think it's interesting :)

**Comment by roblevintennis** [comment]
Ok, so now I read: https://github.com/yangshun/front-end-interview-handbook/blob/master/questions/javascript-questions.md#what-is-the-difference-between--and- where you DO seem to advise that a valid use of abstract operator is for `null` or `undefined`, so I think this sort of contradicts this section which seems to advise it's never a good idea.

**Comment by yangshun** [comment]
> What's the difference between a variable that is: null, undefined or undeclared? How would you go about checking for any of these states?

For this question, I'm advising to use `===` only and not use `==`. Because if you want to check if a value is `null`, using `==` will also give you `true` if the value was `undefined`.

For example, one common case is an API  modifying objects in a database API. If a function has a signature of `function modifyUserInDatabase({ id, name, age })` and you call it like:

```js
modifyUserInDatabase({ id: 1, name: 'Rob', age: null }); // name: 'Rob', age: null
// In this case, age is null and you will want to see the age database column to null
```

```js
modifyUserInDatabase({ id: 1, name: 'Rob' }); // name: 'Rob', age: undefined
// In this case, age is not passed in, meaning you don't want to touch that column at all
```

For the above case, you will need to use strict equality otherwise you are unable to distinguish between setting a value to `null` (with the intention of resetting the value) vs not setting the value at all.

For other cases, if you just want to know if something is `null` or `undefined`, then `==` is ok.

Hope that explains the difference. Let me know if you think that explanation is unclear

**Comment by roblevintennis** [comment]
Ahhhh ok, thanks for the clarification. Makes sense.
